name: Feature
description: New feature or task
title: ""
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: textarea
    id: files
    attributes:
      label: Files
      description: Key files to modify
